sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t cosmin16/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI-true cosmin16/react-test npm test

after_success:
  - docker build -t cosmin16/multi-client ./client
  - docker build -t cosmin16/multi-nginx ./nginx
  - docker build -t cosmin16/multi-server ./server
  - docker build -t cosmin16/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push cosmin16/multi-client
  - docker push cosmin16/multi-nginx
  - docker push cosmin16/multi-server
  - docker push cosmin16/multi-worker 